// File generated by flutterfire_cli.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Load from .env file if available, otherwise use defaults
    return web;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBmdOK5FKLhTbQludLr-x4XHYelAqqLgE',
    appId: '1:403198507706:web:ac6290377f2b9ae4252083',
    messagingSenderId: '403198507706',
    projectId: 'smartmess-project',
    authDomain: 'smartmess-project.firebaseapp.com',
    storageBucket: 'smartmess-project.firebasestorage.app',
  );
}
